export const IDEAS_STUDIO_PROJECT_ID =
  process.env.NEXT_PUBLIC_IDEAS_STUDIO_PROJECT_ID;
export const IDEAS_STUDIO_TRACKING_KEY =
  process.env.NEXT_PUBLIC_IDEAS_STUDIO_TRACKING_KEY;
export const IDEAS_STUDIO_PUBLIC_PROJECT_ENDPOINT =
  process.env.NEXT_PUBLIC_IDEAS_STUDIO_PUBLIC_PROJECT_ENDPOINT;
export const IDEAS_STUDIO_PUBLIC_JS_ENDPOINT =
  process.env.NEXT_PUBLIC_IDEAS_STUDIO_PUBLIC_JS_ENDPOINT;
export const IDEAS_STUDIO_TRACKING_JS_URL =
  process.env.NEXT_PUBLIC_IDEAS_STUDIO_TRACKING_JS_URL;
